
<?php

// config/cities.php

return [
    'Afghanistan' => [
        'Kabul',
        'Herat',
        'Mazar-i-Sharif',
        'Kandahar',
        'Jalalabad',
        'Kunduz',
    ],
    'Albania' => [
        'Tirana',
        'Durres',
        'Vlore',
        'Shkoder',
        'Fier',
        'Korce',
    ],
    'Algeria' => [
        'Algiers',
        'Oran',
        'Constantine',
        'Annaba',
        'Batna',
        'Setif',
    ],
    'Argentina' => [
        'Buenos Aires',
        'Cordoba',
        'Rosario',
        'Mendoza',
        'San Miguel de Tucuman',
        'La Plata',
    ],
    'Australia' => [
        'Sydney',
        'Melbourne',
        'Brisbane',
        'Perth',
        'Adelaide',
        'Gold Coast',
    ],
    'Brazil' => [
        'Sao Paulo',
        'Rio de Janeiro',
        'Brasilia',
        'Salvador',
        'Fortaleza',
        'Belo Horizonte',
    ],
    'Canada' => [
        'Toronto',
        'Montreal',
        'Vancouver',
        'Calgary',
        'Edmonton',
        'Ottawa',
    ],
    'China' => [
        'Beijing',
        'Shanghai',
        'Guangzhou',
        'Shenzhen',
        'Chengdu',
        'Wuhan',
    ],
    'France' => [
        'Paris',
        'Marseille',
        'Lyon',
        'Toulouse',
        'Nice',
        'Nantes',
    ],
    'Germany' => [
        'Berlin',
        'Hamburg',
        'Munich',
        'Cologne',
        'Frankfurt',
        'Stuttgart',
    ],
    'India' => [
        'Mumbai',
        'Delhi',
        'Bangalore',
        'Hyderabad',
        'Chennai',
        'Kolkata',
    ],
    'Italy' => [
        'Rome',
        'Milan',
        'Naples',
        'Turin',
        'Palermo',
        'Genoa',
    ],
    'Japan' => [
        'Tokyo',
        'Yokohama',
        'Osaka',
        'Nagoya',
        'Sapporo',
        'Fukuoka',
    ],
    'Mexico' => [
        'Mexico City',
        'Guadalajara',
        'Monterrey',
        'Puebla',
        'Toluca',
        'Tijuana',
    ],
    'Netherlands' => [
        'Amsterdam',
        'Rotterdam',
        'The Hague',
        'Utrecht',
        'Eindhoven',
        'Tilburg',
    ],
    'Russia' => [
        'Moscow',
        'Saint Petersburg',
        'Novosibirsk',
        'Yekaterinburg',
        'Kazan',
        'Nizhny Novgorod',
    ],
    'South Africa' => [
        'Johannesburg',
        'Cape Town',
        'Durban',
        'Pretoria',
        'Port Elizabeth',
        'Bloemfontein',
    ],
    'Spain' => [
        'Madrid',
        'Barcelona',
        'Valencia',
        'Seville',
        'Zaragoza',
        'Malaga',
    ],
    'Switzerland' => [
        'Zurich',
        'Geneva',
        'Basel',
        'Lausanne',
        'Bern',
        'Lucerne',
    ],
    'United Kingdom' => [
        'London',
        'Manchester',
        'Birmingham',
        'Glasgow',
        'Liverpool',
        'Edinburgh',
    ],
    'United States' => [
        'New York',
        'Los Angeles',
        'Chicago',
        'Houston',
        'Phoenix',
        'Philadelphia',
    ],
];
